### ISSUE TITLE
how to change icon

### ISSUE THREAD

**Issue by ruhengChen** [ZygmuntJakub/Headers#1]
This icon is too inconspicuous， how to change it？
![2024-09-13 15 01 37@2x](https://github.com/user-attachments/assets/f11c15c2-3a3b-4805-8b0a-014371a61e39)

**Comment by ZygmuntJakub** [comment]
I have improved the logotype to contrast well with the light and dark themes. The fix is available after the update to version 1.3. If you have any more problem, let me know! <br />
![icon-128](https://github.com/user-attachments/assets/e052e8d4-f2d8-463c-9b15-2279ceff0f84)
